# Generated by Django 5.1.3 on 2024-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.TextField(default='article')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='media/images')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('path', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('comments_count', models.PositiveIntegerField(blank=True, null=True)),
                ('public_reactions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('positive_reactions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('negative_reactions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
