# Generated by Django 5.1.3 on 2024-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of',
            field=models.CharField(default='article', max_length=6),
        ),
    ]
