# Generated by Django 5.1.3 on 2024-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of',
            field=models.CharField(default='article', max_length=7),
        ),
    ]
